export const TEAM_DESCRIPTIONS: Record<string, string> = {
  ANA: "Founded in 1993 by the Walt Disney Company as the Mighty Ducks of Anaheim, the franchise won its first Stanley Cup in 2007. They play at the Honda Center and are known for their iconic webbed 'D' logo.",
  BOS: "One of the Original Six NHL franchises, the Bruins were founded in 1924. They have a rich history of physical, defensive hockey and have won six Stanley Cups, playing their home games at TD Garden.",
  BUF: "Established in 1970, the Sabres play at the KeyBank Center. They are known for their passionate fanbase in Western New York and iconic 'French Connection' line of the 1970s.",
  CAR: "Originally the Hartford Whalers, the franchise relocated to North Carolina in 1997. The Hurricanes won their first Stanley Cup in 2006 and are known for their loud 'Storm Surge' celebrations.",
  CBJ: "Joining the NHL as an expansion team in 2000, the Blue Jackets play at Nationwide Arena. Their name pays homage to Ohio's rich Civil War history.",
  CGY: "Founded in Atlanta in 1972 before moving to Calgary in 1980, the Flames won the Stanley Cup in 1989. They are known for the 'C of Red' at the Scotiabank Saddledome.",
  CHI: "An Original Six franchise founded in 1926, the Blackhawks have won six Stanley Cups, including a modern dynasty with three titles between 2010 and 2015. They play at the United Center.",
  COL: "Originally the Quebec Nordiques, the franchise moved to Denver in 1995 and immediately won the Stanley Cup. The Avalanche have secured three championships (1996, 2001, 2022).",
  DAL: "Relocated from Minnesota in 1993, the Stars brought NHL hockey to Texas. They won the Stanley Cup in 1999 and play their home games at the American Airlines Center.",
  DET: "An Original Six team established in 1926, the Red Wings are one of the most successful franchises in NHL history with 11 Stanley Cups. They are affectionately known as 'Hockeytown'.",
  EDM: "Joining the NHL in 1979 from the WHA, the Oilers built a dynasty in the 1980s led by Wayne Gretzky, winning five Stanley Cups. They play at Rogers Place.",
  FLA: "Founded in 1993, the Panthers reached the Stanley Cup Final in their third season (the 'Year of the Rat'). They won their first-ever Stanley Cup championship in 2024.",
  LAK: "Part of the 1967 NHL expansion, the Kings became a powerhouse in the 2010s, winning the Stanley Cup in 2012 and 2014. They play at Crypto.com Arena in downtown LA.",
  MIN: "Bringing NHL hockey back to the 'State of Hockey' in 2000, the Wild boast one of the most passionate and dedicated fanbases in the league, playing at the Xcel Energy Center.",
  MTL: "The oldest continuously operating professional ice hockey team in the world, founded in 1909. The Canadiens have won a record 24 Stanley Cups and are a foundational pillar of the sport.",
  NJD: "Originally the Kansas City Scouts and Colorado Rockies, the franchise moved to New Jersey in 1982. The Devils built a defensive dynasty in the late 90s and 2000s, winning three Stanley Cups.",
  NSH: "An expansion team in 1998, the Predators play at Bridgestone Arena. They are famous for their raucous 'Smashville' crowds and strong country music ties.",
  NYI: "Founded in 1972, the Islanders quickly built a dynasty, winning four consecutive Stanley Cups from 1980 to 1983. They now play at the state-of-the-art UBS Arena.",
  NYR: "An Original Six franchise established in 1926, the Rangers play at the world-famous Madison Square Garden. They famously broke a 54-year championship drought in 1994.",
  OTT: "Re-established in 1992 (an original incarnation played from 1883-1934), the modern Senators play in Canada's capital. They reached the Stanley Cup Final in 2007.",
  PHI: "Part of the 1967 expansion, the Flyers became the first non-Original Six team to win the Stanley Cup with the infamous 'Broad Street Bullies' back-to-back championships in 1974 and 1975.",
  PIT: "Established in 1967, the Penguins have been home to some of the greatest players in NHL history (Lemieux, Crosby, Jagr, Malkin) and have captured five Stanley Cup titles.",
  SEA: "The NHL's 32nd franchise, the Kraken began play in the 2021-22 season. They play at the environmentally sustainable Climate Pledge Arena in Seattle.",
  SJS: "Founded in 1991, the Sharks have been a consistently competitive force in the Western Conference. They play their home games at the SAP Center, famously known as 'The Shark Tank'.",
  STL: "Part of the 1967 expansion, the Blues made the Stanley Cup Final in their first three seasons. They famously won their first Stanley Cup in 2019 after being last place in the league midway through the season.",
  TBL: "Founded in 1992, the Lightning have become a modern powerhouse, winning three Stanley Cups (2004, 2020, 2021) and fostering a massive hockey market in Florida.",
  TOR: "An Original Six team and one of the most valuable franchises in hockey, the Maple Leafs have a storied history with 13 Stanley Cups, though their last championship came in 1967.",
  UTA: "Established in 2024, the Utah Mammoth bring NHL hockey to Salt Lake City. They represent the newest chapter in the league's expansion into the Mountain West.",
  VAN: "Joining the NHL in 1970, the Canucks play at Rogers Arena. They have reached the Stanley Cup Final three times (1982, 1994, 2011) and feature one of the league's most dedicated fanbases.",
  VGK: "Entering the league in 2017, the Golden Knights shattered expansion records by reaching the Stanley Cup Final in their inaugural season. They captured their first championship in 2023.",
  WPG: "Originally the Atlanta Thrashers, the franchise relocated to Winnipeg in 2011, bringing the NHL back to the passionate Manitoba market. They play at the Canada Life Centre.",
  WSH: "Founded in 1974, the Capitals spent decades as a competitive force before finally capturing their first Stanley Cup in 2018, led by the legendary goal-scorer Alex Ovechkin."
};
